//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class registrationEntities : DbContext
    {
        public registrationEntities()
            : base("name=registrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buildingEntity> buildingEntities { get; set; }
        public virtual DbSet<courseEntity> courseEntities { get; set; }
        public virtual DbSet<facultyEntity> facultyEntities { get; set; }
        public virtual DbSet<interEntity> interEntities { get; set; }
        public virtual DbSet<roomEntity> roomEntities { get; set; }
        public virtual DbSet<semesterEntity> semesterEntities { get; set; }
        public virtual DbSet<stageBuilding> stageBuildings { get; set; }
        public virtual DbSet<stageCourse> stageCourses { get; set; }
        public virtual DbSet<stageFaculty> stageFaculties { get; set; }
        public virtual DbSet<stageInter> stageInters { get; set; }
        public virtual DbSet<stageRoom> stageRooms { get; set; }
        public virtual DbSet<stageSemester> stageSemesters { get; set; }
        public virtual DbSet<stageTrimester> stageTrimesters { get; set; }
        public virtual DbSet<trimesterEntity> trimesterEntities { get; set; }
    
        public virtual int sp_executeInter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_executeInter");
        }
    
        public virtual int sp_extractBuilding()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_extractBuilding");
        }
    }
}
