//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class stageRoom
    {
        public int roomID { get; set; }
        public string roomNo { get; set; }
        public string roomType { get; set; }
        public string buildingID { get; set; }
        public string seat { get; set; }
        public string active { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
