//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class stageInter
    {
        public int interID { get; set; }
        public string year { get; set; }
        public string semester { get; set; }
        public string section { get; set; }
        public string day1 { get; set; }
        public string day2 { get; set; }
        public string day3 { get; set; }
        public string day4 { get; set; }
        public string day5 { get; set; }
        public string day6 { get; set; }
        public string day7 { get; set; }
        public string starttime { get; set; }
        public string endtime { get; set; }
        public Nullable<int> realReg { get; set; }
        public Nullable<int> TotalReg { get; set; }
        public string studyProgram { get; set; }
        public string courseID { get; set; }
        public string facultyID { get; set; }
        public string roomID { get; set; }
        public string buildingID { get; set; }
        public string active { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
