//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class stageFaculty
    {
        public int facultyID { get; set; }
        public string facultyCode { get; set; }
        public string facultyName { get; set; }
        public string facultyAbbr { get; set; }
        public string active { get; set; }
        public string facultyCodeDuplicate { get; set; }
        public string facultyNameDuplicate { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
    }
}
